/**
 * Model library data — all models supported by Trumbo.
 * Grouped by model family. hosted on our inference infrastructure.
 */

export type ModelEntry = {
	id: string;
	name: string;
};

export type ProviderGroup = {
	name: string;
	labId: string;
	description: string;
	models: ModelEntry[];
};

const labLogo = (labId: string) => `https://models.dev/logos/labs/${labId}.svg`;

export const MODEL_LIBRARY_PROVIDERS: ProviderGroup[] = [
	{
		name: "DeepSeek",
		labId: "deepseek",
		description: "Open reasoning, coding, and MoE models from DeepSeek AI.",
		models: [
			{ id: "deepseek-coder-1b-base", name: "DeepSeek Coder 1.3B Base" },
			{ id: "deepseek-coder-33b-instruct", name: "DeepSeek Coder 33B Instruct" },
			{ id: "deepseek-coder-7b-base", name: "DeepSeek Coder 7B Base" },
			{ id: "deepseek-coder-7b-base-v1p5", name: "DeepSeek Coder 7B Base v1.5" },
			{ id: "deepseek-coder-7b-instruct-v1p5", name: "DeepSeek Coder 7B Instruct v1.5" },
			{ id: "deepseek-coder-v2-lite-base", name: "DeepSeek Coder V2 Lite Base" },
			{ id: "deepseek-coder-v2-lite-instruct", name: "DeepSeek Coder V2 Lite Instruct" },
			{ id: "deepseek-prover-v2", name: "DeepSeek Prover V2" },
			{ id: "deepseek-r1-basic", name: "DeepSeek R1 (Basic)" },
			{ id: "deepseek-r1-0528-distill-qwen3-8b", name: "DeepSeek R1 0528 Distill Qwen3 8B" },
			{ id: "deepseek-r1-distill-llama-70b", name: "DeepSeek R1 Distill Llama 70B" },
			{ id: "deepseek-r1-distill-llama-8b", name: "DeepSeek R1 Distill Llama 8B" },
			{ id: "deepseek-r1-distill-qwen-1p5b", name: "DeepSeek R1 Distill Qwen 1.5B" },
			{ id: "deepseek-r1-distill-qwen-14b", name: "DeepSeek R1 Distill Qwen 14B" },
			{ id: "deepseek-r1-distill-qwen-32b", name: "DeepSeek R1 Distill Qwen 32B" },
			{ id: "deepseek-r1-distill-qwen-7b", name: "DeepSeek R1 Distill Qwen 7B" },
			{ id: "deepseek-v2-lite-chat", name: "DeepSeek V2 Lite Chat" },
			{ id: "deepseek-v2p5", name: "DeepSeek V2.5" },
			{ id: "deepseek-v3", name: "DeepSeek V3" },
			{ id: "deepseek-v3-0324", name: "Deepseek V3 03-24" },
			{ id: "deepseek-v3p1-terminus", name: "DeepSeek V3.1 Terminus" },
			{ id: "deepseek-v4-flash", name: "DeepSeek-V4-Flash" },
		],
	},
	{
		name: "Qwen",
		labId: "alibaba",
		description: "Qwen, QwQ, and Qwen-Coder models from Alibaba Cloud.",
		models: [
			{ id: "code-qwen-1p5-7b", name: "CodeQwen 1.5 7B" },
			{ id: "cogito-v1-preview-qwen-14b", name: "Cogito v1 Preview Qwen 14B" },
			{ id: "cogito-v1-preview-qwen-32b", name: "Cogito v1 Preview Qwen 32B" },
			{ id: "dolphin-2-9-2-qwen2-72b", name: "Dolphin 2.9.2 Qwen2 72B" },
			{ id: "qwen3-4b-instruct-2507", name: "Qwen 3 4B Instruct 2507" },
			{ id: "qwen3p5-122b-a10b", name: "Qwen 3.5 122B A10B" },
			{ id: "qwen3p5-35b-a3b", name: "Qwen 3.5 35B A3B" },
			{ id: "qwen-qwq-32b-preview", name: "Qwen QWQ 32B Preview" },
			{ id: "qwen1p5-72b-chat", name: "Qwen1.5 72B Chat" },
			{ id: "qwen2-72b-instruct", name: "Qwen2 72B Instruct" },
			{ id: "qwen2-7b-instruct", name: "Qwen2 7B Instruct" },
			{ id: "qwen2-vl-2b-instruct", name: "Qwen2-VL 2B Instruct" },
			{ id: "qwen2-vl-72b-instruct", name: "Qwen2-VL 72B Instruct" },
			{ id: "qwen2-vl-7b-instruct", name: "Qwen2-VL 7B Instruct" },
			{ id: "qwen2p5-0p5b-instruct", name: "Qwen2.5 0.5B Instruct" },
			{ id: "qwen2p5-1p5b-instruct", name: "Qwen2.5 1.5B Instruct" },
			{ id: "qwen2p5-14b", name: "Qwen2.5 14B" },
			{ id: "qwen2p5-14b-instruct", name: "Qwen2.5 14B Instruct" },
			{ id: "qwen-v2p5-14b-instruct", name: "Qwen2.5 14B Instruct" },
			{ id: "qwen2p5-32b", name: "Qwen2.5 32B" },
			{ id: "qwen2p5-32b-instruct", name: "Qwen2.5 32B Instruct" },
			{ id: "qwen2p5-72b", name: "Qwen2.5 72B" },
			{ id: "qwen2p5-72b-instruct", name: "Qwen2.5 72B Instruct" },
			{ id: "qwen2p5-7b", name: "Qwen2.5 7B" },
			{ id: "qwen-v2p5-7b", name: "Qwen2.5 7B" },
			{ id: "qwen2p5-7b-instruct", name: "Qwen2.5 7B Instruct" },
			{ id: "qwen2p5-coder-0p5b", name: "Qwen2.5-Coder 0.5B" },
			{ id: "qwen2p5-coder-0p5b-instruct", name: "Qwen2.5-Coder 0.5B Instruct" },
			{ id: "qwen2p5-coder-1p5b", name: "Qwen2.5-Coder 1.5B" },
			{ id: "qwen2p5-coder-1p5b-instruct", name: "Qwen2.5-Coder 1.5B Instruct" },
			{ id: "qwen2p5-coder-14b", name: "Qwen2.5-Coder 14B" },
			{ id: "qwen2p5-coder-14b-instruct", name: "Qwen2.5-Coder 14B Instruct" },
			{ id: "qwen2p5-coder-32b", name: "Qwen2.5-Coder 32B" },
			{ id: "qwen2p5-coder-32b-instruct", name: "Qwen2.5-Coder 32B Instruct" },
			{ id: "qwen2p5-coder-32b-instruct-128k", name: "Qwen2.5-Coder 32B Instruct 128K" },
			{ id: "qwen2p5-coder-32b-instruct-32k-rope", name: "Qwen2.5-Coder 32B Instruct 32K RoPE" },
			{ id: "qwen2p5-coder-32b-instruct-64k", name: "Qwen2.5-Coder 32B Instruct 64k" },
			{ id: "qwen2p5-coder-3b", name: "Qwen2.5-Coder 3B" },
			{ id: "qwen2p5-coder-3b-instruct", name: "Qwen2.5-Coder 3B Instruct" },
			{ id: "qwen2p5-coder-7b", name: "Qwen2.5-Coder 7B" },
			{ id: "qwen2p5-coder-7b-instruct", name: "Qwen2.5-Coder 7B Instruct" },
			{ id: "qwen2p5-math-72b-instruct", name: "Qwen2.5-Math 72B Instruct" },
			{ id: "qwen2p5-vl-32b-instruct", name: "Qwen2.5-VL 32B Instruct" },
			{ id: "qwen2p5-vl-3b-instruct", name: "Qwen2.5-VL 3B Instruct" },
			{ id: "qwen2p5-vl-72b-instruct", name: "Qwen2.5-VL 72B Instruct" },
			{ id: "qwen2p5-vl-7b-instruct", name: "Qwen2.5-VL 7B Instruct" },
			{ id: "qwen3-0p6b", name: "Qwen3 0.6B" },
			{ id: "qwen3-1p7b", name: "Qwen3 1.7B" },
			{ id: "qwen3-14b", name: "Qwen3 14B" },
			{ id: "qwen3-30b-a3b-instruct-2507", name: "Qwen3 30B A3B Instruct 2507" },
			{ id: "qwen3-30b-a3b-thinking-2507", name: "Qwen3 30B A3B Thinking 2507" },
			{ id: "qwen3-30b-a3b", name: "Qwen3 30B-A3B" },
			{ id: "qwen3-32b", name: "Qwen3 32B" },
			{ id: "qwen3-4b", name: "Qwen3 4B" },
			{ id: "qwen3-8b", name: "Qwen3 8B" },
			{ id: "qwen3-coder-480b-instruct-bf16", name: "Qwen3 Coder 480B Instruct BF16" },
			{ id: "qwen3-embedding-0p6b", name: "Qwen3 Embedding 0.6B" },
			{ id: "qwen3-embedding-4b", name: "Qwen3 Embedding 4B" },
			{ id: "qwen3-embedding-8b", name: "Qwen3 Embedding 8B" },
			{ id: "qwen3-next-80b-a3b-instruct", name: "Qwen3 Next 80B A3B Instruct" },
			{ id: "qwen3-next-80b-a3b-thinking", name: "Qwen3 Next 80B A3B Thinking" },
			{ id: "qwen3-omni-30b-a3b-instruct", name: "Qwen3 Omni 30B A3B Instruct" },
		],
	},
	{
		name: "Llama",
		labId: "meta",
		description: "Llama, Code Llama, and Llama Guard models from Meta.",
		models: [
			{ id: "code-llama-13b", name: "Code Llama 13B" },
			{ id: "code-llama-13b-instruct", name: "Code Llama 13B Instruct" },
			{ id: "code-llama-13b-python", name: "Code Llama 13B Python" },
			{ id: "code-llama-34b", name: "Code Llama 34B" },
			{ id: "code-llama-34b-instruct", name: "Code Llama 34B Instruct" },
			{ id: "code-llama-34b-python", name: "Code Llama 34B Python" },
			{ id: "code-llama-70b", name: "Code Llama 70B" },
			{ id: "code-llama-70b-instruct", name: "Code Llama 70B Instruct" },
			{ id: "code-llama-70b-python", name: "Code Llama 70B Python" },
			{ id: "code-llama-7b", name: "Code Llama 7B" },
			{ id: "code-llama-7b-instruct", name: "Code Llama 7B Instruct" },
			{ id: "cogito-v1-preview-llama-3b", name: "Cogito v1 Preview Llama 3B" },
			{ id: "cogito-v1-preview-llama-70b", name: "Cogito v1 Preview Llama 70B" },
			{ id: "cogito-v1-preview-llama-8b", name: "Cogito v1 Preview Llama 8B" },
			{ id: "llama-v2-13b", name: "Llama 2 13B" },
			{ id: "llama-v2-13b-chat", name: "Llama 2 13B Chat" },
			{ id: "llama-v2-70b", name: "Llama 2 70B" },
			{ id: "llama-v2-7b", name: "Llama 2 7B" },
			{ id: "llama-v2-7b-chat", name: "Llama 2 7B Chat" },
			{ id: "llama-v3-70b-instruct", name: "Llama 3 70B Instruct" },
			{ id: "llama-v3-70b-instruct-hf", name: "Llama 3 70B Instruct (HF version)" },
			{ id: "llama-v3-8b", name: "Llama 3 8B" },
			{ id: "llama-v3-8b-instruct", name: "Llama 3 8B Instruct" },
			{ id: "llama-v3-8b-instruct-hf", name: "Llama 3 8B Instruct (HF version)" },
			{ id: "llama-v3p1-405b-instruct", name: "Llama 3.1 405B Instruct" },
			{ id: "llama-v3p1-405b-instruct-long", name: "Llama 3.1 405B Instruct Long" },
			{ id: "llama-v3p1-70b-instruct", name: "Llama 3.1 70B Instruct" },
			{ id: "llama-v3p1-70b-instruct-1b", name: "Llama 3.1 70B Instruct 1B" },
			{ id: "llama-v3p1-8b-instruct", name: "Llama 3.1 8B Instruct" },
			{ id: "llama-v3p1-nemotron-70b-instruct", name: "Llama 3.1 Nemotron 70B" },
			{ id: "llama-v3p2-11b-vision-instruct", name: "Llama 3.2 11B Vision Instruct" },
			{ id: "llama-v3p2-1b", name: "Llama 3.2 1B" },
			{ id: "llama-v3p2-1b-instruct", name: "Llama 3.2 1B Instruct" },
			{ id: "llama-v3p2-3b", name: "Llama 3.2 3B" },
			{ id: "llama-v3p2-3b-instruct", name: "Llama 3.2 3B Instruct" },
			{ id: "llama-v3p2-90b-vision-instruct", name: "Llama 3.2 90B Vision Instruct" },
			{ id: "llama4-maverick-instruct-basic", name: "Llama 4 Maverick Instruct (Basic)" },
			{ id: "llama4-scout-instruct-basic", name: "Llama 4 Scout Instruct (Basic)" },
			{ id: "llama-guard-3-8b", name: "Llama Guard 3 8B" },
			{ id: "llamaguard-7b", name: "Llama Guard 7B" },
			{ id: "llama-guard-2-8b", name: "Llama Guard v2 8B" },
			{ id: "llama-guard-3-1b", name: "Llama Guard v3 1B" },
			{ id: "nous-hermes-llama2-13b", name: "Nous Hermes Llama2 13B" },
			{ id: "nous-hermes-llama2-70b", name: "Nous Hermes Llama2 70B" },
			{ id: "nous-hermes-llama2-7b", name: "Nous Hermes Llama2 7B" },
			{ id: "phind-code-llama-34b-python-v1", name: "Phind CodeLlama 34B Python v1" },
			{ id: "phind-code-llama-34b-v1", name: "Phind CodeLlama 34B v1" },
			{ id: "phind-code-llama-34b-v2", name: "Phind CodeLlama 34B v2" },
		],
	},
	{
		name: "Mistral",
		labId: "mistral",
		description: "Mistral, Mixtral, and derived models from Mistral AI.",
		models: [
			{ id: "dolphin-2p6-mixtral-8x7b", name: "Dolphin 2.6 Mixtral 8x7b" },
			{ id: "hermes-2-pro-mistral-7b", name: "Hermes 2 Pro Mistral 7B" },
			{ id: "mistral-7b", name: "Mistral 7B" },
			{ id: "mistral-7b-instruct-v0p2", name: "Mistral 7B Instruct v0.2" },
			{ id: "mistral-7b-instruct-v3", name: "Mistral 7B Instruct v0.3" },
			{ id: "openorca-7b", name: "Mistral 7B OpenOrca" },
			{ id: "mistral-7b-v0p2", name: "Mistral 7B v0.2" },
			{ id: "mistral-large-3-fp8", name: "Mistral Large 3 675B Instruct 2512" },
			{ id: "mistral-nemo-base-2407", name: "Mistral Nemo Base 2407" },
			{ id: "mistral-nemo-instruct-2407", name: "Mistral Nemo Instruct 2407" },
			{ id: "mistral-small-24b-instruct-2501", name: "Mistral Small 24B Instruct 2501" },
			{ id: "mixtral-8x7b", name: "Mixtral 8x7B v0.1" },
			{ id: "mixtral-8x22b", name: "Mixtral Moe 8x22B" },
			{ id: "mixtral-8x22b-instruct", name: "Mixtral MoE 8x22B Instruct" },
			{ id: "mixtral-8x7b-instruct", name: "Mixtral MoE 8x7B Instruct" },
			{ id: "mixtral-8x7b-instruct-hf", name: "Mixtral MoE 8x7B Instruct (HF version)" },
			{ id: "nous-hermes-2-mixtral-8x7b-dpo", name: "Nouse Hermes 2 Mixtral 8x7B DPO" },
			{ id: "openhermes-2-mistral-7b", name: "OpenHermes 2 Mistral 7B" },
			{ id: "openhermes-2p5-mistral-7b", name: "OpenHermes 2.5 Mistral 7B" },
		],
	},
	{
		name: "Zhipu AI (GLM)",
		labId: "zhipuai",
		description: "GLM foundation models from Zhipu AI, designed for agents.",
		models: [
			{ id: "glm-5p2-fp8", name: "GLM 5.2 FP8" },
			{ id: "glm-4p5", name: "GLM-4.5" },
			{ id: "glm-4p5-air", name: "GLM-4.5-Air" },
			{ id: "glm-4p5v", name: "GLM-4.5V" },
			{ id: "glm-4p7", name: "GLM-4.7" },
			{ id: "glm-4p7-flash", name: "GLM-4.7 Flash" },
		],
	},
	{
		name: "Moonshot AI (Kimi)",
		labId: "moonshotai",
		description: "Kimi MoE models from Moonshot AI.",
		models: [
			{ id: "kimi-k2-instruct", name: "Kimi K2 Instruct" },
		],
	},
	{
		name: "MiniMax",
		labId: "minimax",
		description: "Hybrid-attention reasoning models from MiniMax.",
		models: [
			{ id: "minimax-m1-80k", name: "MiniMax-M1-80k" },
			{ id: "minimax-m2", name: "MiniMax-M2" },
		],
	},
	{
		name: "OpenAI",
		labId: "openai",
		description: "Open-weights safety and safeguard models from OpenAI.",
		models: [
			{ id: "gpt-oss-safeguard-120b", name: "OpenAI gpt-oss-safeguard-120b" },
			{ id: "gpt-oss-safeguard-20b", name: "OpenAI gpt-oss-safeguard-20b" },
		],
	},
	{
		name: "Other",
		labId: "fireworks",
		description: "Gemma, Phi, NVIDIA Nemotron, vision, image, and specialized models.",
		models: [
			{ id: "chronos-hermes-13b-v2", name: "Chronos Hermes 13B v2" },
			{ id: "codegemma-2b", name: "CodeGemma 2B" },
			{ id: "codegemma-7b", name: "CodeGemma 7B" },
			{ id: "devstral-small-2-24b-instruct-2512", name: "Devstral Small 2 24B Instruct 2512" },
			{ id: "devstral-small-2505", name: "Devstral-Small-2505" },
			{ id: "ernie-4p5-21b-a3b-pt", name: "ERNIE-4.5-21B-A3B-PT" },
			{ id: "ernie-4p5-300b-a47b-pt", name: "ERNIE-4.5-300B-A47B-PT" },
			{ id: "fare-20b", name: "FARE-20B" },
			{ id: "firefunction-v1", name: "FireFunction V1" },
			{ id: "firefunction-v2", name: "FireFunction V2" },
			{ id: "firesearch-ocr-v6", name: "Firesearch OCR V6" },
			{ id: "flux-1-dev-controlnet-union", name: "FLUX.1 [dev] ControlNet" },
			{ id: "flux-1-schnell", name: "FLUX.1 [schnell]" },
			{ id: "gemma2-9b-it", name: "Gemma 2 9B Instruct" },
			{ id: "gemma-2b-it", name: "Gemma 2B Instruct" },
			{ id: "gemma-3-12b-it", name: "Gemma 3 12B Instruct" },
			{ id: "gemma-3-1b-it", name: "Gemma 3 1B Instruct" },
			{ id: "gemma-3-27b-it", name: "Gemma 3 27B Instruct" },
			{ id: "gemma-3-4b-it", name: "Gemma 3 4B Instruct" },
			{ id: "gemma-4-e4b", name: "Gemma 4 E4B" },
			{ id: "gemma-7b", name: "Gemma 7B" },
			{ id: "gemma-7b-it", name: "Gemma 7B Instruct" },
			{ id: "internvl3-38b", name: "InternVL3 38B" },
			{ id: "internvl3-78b", name: "InternVL3 78B" },
			{ id: "internvl3-8b", name: "InternVL3 8B" },
			{ id: "japanese-stable-diffusion-xl", name: "Japanese Stable Diffusion XL" },
			{ id: "kat-dev-32b", name: "KAT Dev 32B" },
			{ id: "ministral-3-14b-instruct-2512", name: "Ministral 3 14B Instruct 2512" },
			{ id: "ministral-3-3b-instruct-2512", name: "Ministral 3 3B Instruct 2512" },
			{ id: "ministral-3-8b-instruct-2512", name: "Ministral 3 8B Instruct 2512" },
			{ id: "mirothinker-1p7", name: "MiroThinker-1.7" },
			{ id: "molmo2-4b", name: "Molmo2-4B" },
			{ id: "molmo2-8b", name: "Molmo2-8B" },
			{ id: "mythomax-l2-13b", name: "MythoMax L2 13B" },
			{ id: "nous-capybara-7b-v1p9", name: "Nous Capybara 7B V1.9" },
			{ id: "nvidia-nemotron-3-nano-omni-30b-a3b", name: "NVIDIA Nemotron 3 Nano Omni 30B A3B" },
			{ id: "nemotron-3-super-120b-a12b-bf16", name: "NVIDIA Nemotron 3 Super 120B A12B BF16" },
			{ id: "nvidia-nemotron-nano-12b-v2", name: "NVIDIA Nemotron Nano 12B v2" },
			{ id: "nemotron-nano-v2-12b-vl", name: "NVIDIA Nemotron Nano 2 VL" },
			{ id: "nemotron-nano-3-30b-a3b", name: "NVIDIA Nemotron Nano 3 30B A3B" },
			{ id: "nvidia-nemotron-nano-9b-v2", name: "NVIDIA Nemotron Nano 9B v2" },
			{ id: "openchat-3p5-0106-7b", name: "OpenChat 3.5 0106" },
			{ id: "paddleocr-vl-1-6", name: "PaddleOCR VL 1.6" },
			{ id: "phi-3-mini-128k-instruct", name: "Phi-3 Mini 128k Instruct" },
			{ id: "phi-3-vision-128k-instruct", name: "Phi-3.5 Vision Instruct" },
			{ id: "playground-v2-1024px-aesthetic", name: "Playground v2 1024" },
			{ id: "playground-v2-5-1024px-aesthetic", name: "Playground v2.5 1024" },
			{ id: "pythia-12b", name: "Pythia 12B" },
		],
	},
];

export function providerLogoUrl(labId: string): string {
	return labLogo(labId);
}

export const TOTAL_MODEL_COUNT = MODEL_LIBRARY_PROVIDERS.reduce(
	(sum, p) => sum + p.models.length,
	0,
);
